In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../../DATA/processed_telco.csv")

In [3]:
df.head()

,Gender,Senior Citizen,Partner,Dependents,Tenure Months,Phone Service,Multiple Lines,Online Security,Online Backup,Device Protection,...,Contract_One year,Contract_Two year,Payment Method_Bank transfer (automatic),Payment Method_Credit card (automatic),Payment Method_Electronic check,Payment Method_Mailed check,Internet Service_DSL,Internet Service_Fiber optic,Internet Service_No,Average Charges
0,0.990658,-0.440327,-0.965608,-0.547115,-1.239504,0.327189,-0.991564,1.408012,1.242875,-1.026988,...,False,False,False,False,False,True,True,False,False,4.006817
1,-1.009430,-0.440327,-0.965608,1.827769,-1.239504,0.327189,-0.991564,-0.917837,-1.028998,-1.026988,...,False,False,False,False,True,False,False,True,False,3.926687
2,-1.009430,-0.440327,-0.965608,1.827769,-0.995040,0.327189,1.116896,-0.917837,-1.028998,1.245441,...,False,False,False,False,True,False,False,True,False,-130.122842
3,-1.009430,-0.440327,1.035617,1.827769,-0.180161,0.327189,1.116896,-0.917837,-1.028998,1.245441,...,False,False,False,False,True,False,False,True,False,0.410465
4,0.990658,-0.440327,-0.965608,1.827769,0.675462,0.327189,1.116896,-0.917837,1.242875,1.245441,...,False,False,True,False,False,False,False,True,False,0.724928

Are there any opportunities to create new features?

In [4]:
df.columns

Index(['Gender', 'Senior Citizen', 'Partner', 'Dependents', 'Tenure Months',
       'Phone Service', 'Multiple Lines', 'Online Security', 'Online Backup',
       'Device Protection', 'Tech Support', 'Streaming TV', 'Streaming Movies',
       'Paperless Billing', 'Monthly Charges', 'Total Charges', 'Churn Label',
       'CLTV', 'Contract_Month-to-month', 'Contract_One year',
       'Contract_Two year', 'Payment Method_Bank transfer (automatic)',
       'Payment Method_Credit card (automatic)',
       'Payment Method_Electronic check', 'Payment Method_Mailed check',
       'Internet Service_DSL', 'Internet Service_Fiber optic',
       'Internet Service_No', 'Average Charges'],
      dtype='object')

Can we calculate the average monthly spending for each customer?

In [5]:
df["Average Charges"] = (
    df["Total Charges"] /
    (df["Tenure Months"] + 1)
)

Does the new feature look reasonable?

In [6]:
df["Average Charges"].describe()

count    7032.000000
mean       -2.011540
std        22.031629
min      -191.990773
25%        -0.450478
50%         0.340080
75%         0.941223
max        26.957560
Name: Average Charges, dtype: float64

Are all features already encoded?

In [7]:
df.select_dtypes(include="object").columns

Index([], dtype='object')

Are all numerical features scaled?

In [8]:
df.describe()

,Gender,Senior Citizen,Partner,Dependents,Tenure Months,Phone Service,Multiple Lines,Online Security,Online Backup,Device Protection,Tech Support,Streaming TV,Streaming Movies,Paperless Billing,Monthly Charges,Total Charges,Churn Label,CLTV,Average Charges
count,7.032000e+03,7.032000e+03,7.032000e+03,7.032000e+03,7.032000e+03,7.032000e+03,7.032000e+03,7032.000000,7.032000e+03,7.032000e+03,7.032000e+03,7.032000e+03,7.032000e+03,7032.000000,7.032000e+03,7.032000e+03,7032.000000,7.032000e+03,7032.000000
mean,-7.073093e-17,1.616707e-17,6.466828e-17,-3.233414e-17,-1.293366e-16,6.871005e-17,4.850121e-17,0.000000,-4.041768e-17,-1.293366e-16,-8.083535e-17,2.020884e-18,7.679358e-17,0.000000,4.850121e-17,1.050860e-16,0.265785,4.041768e-17,-2.011540
std,1.000071e+00,1.000071e+00,1.000071e+00,1.000071e+00,1.000071e+00,1.000071e+00,1.000071e+00,1.000071,1.000071e+00,1.000071e+00,1.000071e+00,1.000071e+00,1.000071e+00,1.000071,1.000071e+00,1.000071e+00,0.441782,1.000071e+00,22.031629
min,-1.009430e+00,-4.403271e-01,-9.656081e-01,-5.471150e-01,-1.280248e+00,-3.056334e+00,-9.915636e-01,-0.917837,-1.028998e+00,-1.026988e+00,-9.242666e-01,-1.112632e+00,-1.121501e+00,-1.206361,-1.547283e+00,-9.990692e-01,0.000000,-2.028575e+00,-191.990773
25%,-1.009430e+00,-4.403271e-01,-9.656081e-01,-5.471150e-01,-9.542963e-01,3.271894e-01,-9.915636e-01,-0.917837,-1.028998e+00,-1.026988e+00,-9.242666e-01,-1.112632e+00,-1.121501e+00,-1.206361,-9.709769e-01,-8.302488e-01,0.000000,-7.880160e-01,-0.450478
50%,9.906580e-01,-4.403271e-01,-9.656081e-01,-5.471150e-01,-1.394171e-01,3.271894e-01,6.266610e-02,0.245087,1.069383e-01,1.092265e-01,2.363482e-01,1.702844e-02,8.031376e-03,0.828939,1.845440e-01,-3.908151e-01,0.000000,1.066156e-01,0.340080
75%,9.906580e-01,-4.403271e-01,1.035617e+00,-5.471150e-01,9.199259e-01,3.271894e-01,1.116896e+00,1.408012,1.242875e+00,1.245441e+00,1.396963e+00,1.146689e+00,1.137564e+00,0.828939,8.331482e-01,6.668271e-01,1.000000,8.284952e-01,0.941223
max,9.906580e-01,2.271039e+00,1.035617e+00,1.827769e+00,1.612573e+00,3.271894e-01,1.116896e+00,1.408012,1.242875e+00,1.245441e+00,1.396963e+00,1.146689e+00,1.137564e+00,0.828939,1.793381e+00,2.824261e+00,1.000000,1.774931e+00,26.957560

Do we still have boolean columns?

In [9]:
bool_columns = df.select_dtypes(include="bool").columns

bool_columns

Index(['Contract_Month-to-month', 'Contract_One year', 'Contract_Two year',
       'Payment Method_Bank transfer (automatic)',
       'Payment Method_Credit card (automatic)',
       'Payment Method_Electronic check', 'Payment Method_Mailed check',
       'Internet Service_DSL', 'Internet Service_Fiber optic',
       'Internet Service_No'],
      dtype='object')

Can we convert boolean features into integers?

In [10]:
df[bool_columns] = df[bool_columns].astype(int)

In [11]:
df.dtypes

Gender                                      float64
Senior Citizen                              float64
Partner                                     float64
Dependents                                  float64
Tenure Months                               float64
Phone Service                               float64
Multiple Lines                              float64
Online Security                             float64
Online Backup                               float64
Device Protection                           float64
Tech Support                                float64
Streaming TV                                float64
Streaming Movies                            float64
Paperless Billing                           float64
Monthly Charges                             float64
Total Charges                               float64
Churn Label                                   int64
CLTV                                        float64
Contract_Month-to-month                       int64
Contract_One year                             int64
Contract_Two year                             int64
Payment Method_Bank transfer (automatic)      int64
Payment Method_Credit card (automatic)        int64
Payment Method_Electronic check               int64
Payment Method_Mailed check                   int64
Internet Service_DSL                          int64
Internet Service_Fiber optic                  int64
Internet Service_No                           int64
Average Charges                             float64
dtype: object

Is the dataset ready for machine learning?

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7032 entries, 0 to 7031
Data columns (total 29 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Gender                                    7032 non-null   float64
 1   Senior Citizen                            7032 non-null   float64
 2   Partner                                   7032 non-null   float64
 3   Dependents                                7032 non-null   float64
 4   Tenure Months                             7032 non-null   float64
 5   Phone Service                             7032 non-null   float64
 6   Multiple Lines                            7032 non-null   float64
 7   Online Security                           7032 non-null   float64
 8   Online Backup                             7032 non-null   float64
 9   Device Protection                         7032 non-null   float64
 10  Tech Support                              7032 non-null   float64
 11  Streaming TV                              7032 non-null   float64
 12  Streaming Movies                          7032 non-null   float64
 13  Paperless Billing                         7032 non-null   float64
 14  Monthly Charges                           7032 non-null   float64
 15  Total Charges                             7032 non-null   float64
 16  Churn Label                               7032 non-null   int64
 17  CLTV                                      7032 non-null   float64
 18  Contract_Month-to-month                   7032 non-null   int64
 19  Contract_One year                         7032 non-null   int64
 20  Contract_Two year                         7032 non-null   int64
 21  Payment Method_Bank transfer (automatic)  7032 non-null   int64
 22  Payment Method_Credit card (automatic)    7032 non-null   int64
 23  Payment Method_Electronic check           7032 non-null   int64
 24  Payment Method_Mailed check               7032 non-null   int64
 25  Internet Service_DSL                      7032 non-null   int64
 26  Internet Service_Fiber optic              7032 non-null   int64
 27  Internet Service_No                       7032 non-null   int64
 28  Average Charges                           7032 non-null   float64
dtypes: float64(18), int64(11)
memory usage: 1.6 MB

Can we estimate the customer's value per month?

In [13]:
df["CLTV per Month"] = df["CLTV"] / (df["Tenure Months"] + 1)

In [14]:
df[["CLTV","Tenure Months","CLTV per Month"]].head()

       CLTV  Tenure Months  CLTV per Month
0 -0.983181      -1.239504        4.105072
1 -1.438215      -1.239504        6.004971
2  0.820883      -0.995040      165.510906
3  0.508788      -0.180161        0.620595
4  0.793818       0.675462        0.473790

Can we identify high-paying customers?

In [15]:
median_charge = df["Monthly Charges"].median()

df["High Monthly Charge"] = np.where(
    df["Monthly Charges"] > median_charge,
    1,
    0
)

In [16]:
df["High Monthly Charge"].value_counts()

High Monthly Charge
0    3519
1    3513
Name: count, dtype: int64

Can we identify loyal customers?

In [17]:
median_tenure = df["Tenure Months"].median()

df["Loyal Customer"] = np.where(
    df["Tenure Months"] > median_tenure,
    1,
    0
)

In [18]:
df["Loyal Customer"].value_counts()

Loyal Customer
0    3558
1    3474
Name: count, dtype: int64

How many new engineered features were created?

In [19]:
new_features = [
    "Average Charges",
    "CLTV per Month",
    "High Monthly Charge",
    "Loyal Customer"
]

df[new_features].head()

   Average Charges  CLTV per Month  High Monthly Charge  Loyal Customer
0         4.006817        4.105072                    0               0
1         3.926687        6.004971                    1               0
2      -130.122842      165.510906                    1               0
3         0.410465        0.620595                    1               0
4         0.724928        0.473790                    1               1

Can we save the feature engineered dataset?

In [20]:
df.to_csv("../../DATA/featured_telco.csv", index=False)

Key Insights (تكتبيها آخر الـ Notebook)
A new feature (Average Charges) was created to better represent customer spending behavior.
All categorical variables were already encoded during preprocessing.
Numerical features were already standardized using feature scaling.
Boolean columns were converted into integer values.
The final dataset contains only numerical features and is fully prepared for machine learning models.

Key Insights
Created Average Charges to represent customer monthly spending.
Created CLTV per Month to estimate customer value over time.
Created Service Count to summarize the number of subscribed services.
Created Has Many Services to classify customers based on service usage.
Created High Monthly Charge to distinguish high-paying customers.
Created Loyal Customer based on customer tenure.
The dataset now contains richer behavioral features that can improve churn predictio

In [21]:
df.columns.tolist()

['Gender',
 'Senior Citizen',
 'Partner',
 'Dependents',
 'Tenure Months',
 'Phone Service',
 'Multiple Lines',
 'Online Security',
 'Online Backup',
 'Device Protection',
 'Tech Support',
 'Streaming TV',
 'Streaming Movies',
 'Paperless Billing',
 'Monthly Charges',
 'Total Charges',
 'Churn Label',
 'CLTV',
 'Contract_Month-to-month',
 'Contract_One year',
 'Contract_Two year',
 'Payment Method_Bank transfer (automatic)',
 'Payment Method_Credit card (automatic)',
 'Payment Method_Electronic check',
 'Payment Method_Mailed check',
 'Internet Service_DSL',
 'Internet Service_Fiber optic',
 'Internet Service_No',
 'Average Charges',
 'CLTV per Month',
 'High Monthly Charge',
 'Loyal Customer']