Which machine learning model achieved the highest performance?


How do the models compare using evaluation metrics?

Which model should be selected for deployment?

Can the selected model be saved for future use?

In [1]:
import pandas as pd
import joblib

from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

from imblearn.over_sampling import SMOTE

In [2]:
df = pd.read_csv("../../DATA/featured_telco.csv")

df.head()

,Gender,Senior Citizen,Partner,Dependents,Tenure Months,Phone Service,Multiple Lines,Online Security,Online Backup,Device Protection,...,Payment Method_Credit card (automatic),Payment Method_Electronic check,Payment Method_Mailed check,Internet Service_DSL,Internet Service_Fiber optic,Internet Service_No,Average Charges,CLTV per Month,High Monthly Charge,Loyal Customer
0,0.990658,-0.440327,-0.965608,-0.547115,-1.239504,0.327189,-0.991564,1.408012,1.242875,-1.026988,...,0,0,1,1,0,0,4.006817,4.105072,0,0
1,-1.009430,-0.440327,-0.965608,1.827769,-1.239504,0.327189,-0.991564,-0.917837,-1.028998,-1.026988,...,0,1,0,0,1,0,3.926687,6.004971,1,0
2,-1.009430,-0.440327,-0.965608,1.827769,-0.995040,0.327189,1.116896,-0.917837,-1.028998,1.245441,...,0,1,0,0,1,0,-130.122842,165.510906,1,0
3,-1.009430,-0.440327,1.035617,1.827769,-0.180161,0.327189,1.116896,-0.917837,-1.028998,1.245441,...,0,1,0,0,1,0,0.410465,0.620595,1,0
4,0.990658,-0.440327,-0.965608,1.827769,0.675462,0.327189,1.116896,-0.917837,1.242875,1.245441,...,0,0,0,0,1,0,0.724928,0.473790,1,1

In [3]:
X = df.drop(columns=["Churn Label"])

y = df["Churn Label"]

In [4]:
X_train, X_test, y_train, y_test = train_test_split(

    X,
    y,

    test_size=0.2,

    random_state=42,

    stratify=y

)

In [5]:
smote = SMOTE(random_state=42)

X_train_smote, y_train_smote = smote.fit_resample(
    X_train,
    y_train
)

Train the tuned Logistic Regression model

In [6]:
{'C':1,'solver':'liblinear'}

{'C': 1, 'solver': 'liblinear'}

In [7]:
logistic = LogisticRegression(

    C=1,

    solver="liblinear",

    max_iter=1000

)

logistic.fit(
    X_train_smote,
    y_train_smote
)

LogisticRegression(C=1, max_iter=1000, solver='liblinear')

Train the tuned Random Forest model

In [8]:
rf = RandomForestClassifier(

    n_estimators=200,

    max_depth=20,

    min_samples_split=5,

    random_state=42

)

rf.fit(
    X_train_smote,
    y_train_smote
)

RandomForestClassifier(max_depth=20, min_samples_split=5, n_estimators=200,
                       random_state=42)

Compare both tuned models

In [9]:
models = {

    "Logistic Regression": logistic,

    "Random Forest": rf

}

results = []

for name, model in models.items():

    predictions = model.predict(X_test)

    probabilities = model.predict_proba(X_test)[:,1]

    results.append({

        "Model": name,

        "Accuracy": accuracy_score(y_test, predictions),

        "Precision": precision_score(y_test, predictions),

        "Recall": recall_score(y_test, predictions),

        "F1 Score": f1_score(y_test, predictions),

        "ROC AUC": roc_auc_score(
            y_test,
            probabilities
        )

    })

comparison = pd.DataFrame(results)

comparison = comparison.sort_values(
    by="Accuracy",
    ascending=False
)

comparison

                 Model  Accuracy  Precision    Recall  F1 Score   ROC AUC
1        Random Forest  0.789623   0.597015  0.641711  0.618557  0.837328
0  Logistic Regression  0.779673   0.568966  0.705882  0.630072  0.842262

The tuned machine learning models were compared using multiple evaluation metrics. The comparison provides a clear overview of each model's strengths and weaknesses before selecting the final deployment model.

Which model should be selected for deployment?

In [10]:
best_model = rf

In [11]:
joblib.dump(

    best_model,

    "../../models/best_model.pkl"

)

['../../models/best_model.pkl']

Final Key Insights


Two optimized machine learning models were compared using multiple evaluation metrics.


Hyperparameter tuning improved the overall performance of both models.


Random Forest achieved the strongest overall performance across the evaluation metrics and was selected as the final model for deployment.


The selected model was successfully saved as best_model.pkl for future deployment and inference.


The model is now ready to be integrated into the deployment pipeline in the next milestone.